// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: .proto

package com.fullstackclj.proto;

public final class FullstackcljProtobuf {
  private FullstackcljProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_clj_proto_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_clj_proto_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\006.proto\022\tclj_proto\"e\n\007Request\022-\n\004Type\030\001" +
      " \002(\0162\037.clj_proto.Request.REQUEST_TYPE\022\014\n" +
      "\004Data\030\002 \002(\t\"\035\n\014REQUEST_TYPE\022\r\n\tTYPE_TEST" +
      "\020\000B0\n\026com.fullstackclj.protoB\024Fullstackc" +
      "ljProtobufP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_clj_proto_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_clj_proto_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_clj_proto_Request_descriptor,
        new java.lang.String[] { "Type", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
