// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: .proto

package com.fullstackclj.proto;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:clj_proto.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required .clj_proto.Request.REQUEST_TYPE Type = 1;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>required .clj_proto.Request.REQUEST_TYPE Type = 1;</code>
   * @return The type.
   */
  com.fullstackclj.proto.Request.REQUEST_TYPE getType();

  /**
   * <code>required string Data = 2;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>required string Data = 2;</code>
   * @return The data.
   */
  java.lang.String getData();
  /**
   * <code>required string Data = 2;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
